#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import socket
from argparse import ArgumentParser

def read_word_list(file_path=None):
    """
    Resolve uma world list com os hosts.

    Param:
        file_path: <str> :Caminho até o arquivo de world list.
    Return:
        word_list: <list> :Retorna uma lista dos hosts.
    """
    word_list = None
    with open(file_path) as reader:
        word_list = [line.strip('\n') for line in reader.readlines()]
    return word_list


def enumerate_domain(domain=None, word_list=None):
    """
    Realiza a enumeração do dominio desejado.

    Params:
        domain: <str> :Nome do dominio. Ex: google.com
        word_list: <list> :Lista de hots: Ex: [www, ftp]
    """
    for name in word_list:
        try:
            dns = '%s.%s' % (name, domain)
            internet_protocol = socket.gethostbyname(dns)
            print('%s \t | %s' % (dns, internet_protocol))
        except socket.gaierror:
            pass


if __name__ == '__main__':
    dns_enum = ArgumentParser(
        description='Enumera dominios.',
    )
    dns_enum.add_argument(
        'domain',
        type=str,
        help='Nome de dominio. Ex: google.com',
    )
    dns_enum.add_argument(
        '--word_list',
        '-wl',
        action='store',
        default='.word_list.txt',
        help='word_list de hosts.',
    )
    dns_enum.version = '0.0.1'

    args = dns_enum.parse_args()
    word_list = read_word_list(args.word_list)
    enumerate_domain(args.domain, word_list)
